#include "Controllers/ToS_PlayerController.h"
#include "Controllers/ToS_GameInstance.h"
#include "Enum/EntityState.h"
#include "Enum/EntityDelta.h"
#include "Engine/World.h"
#include "Utils/FileLogger.h"

void ATOSPlayerController::BeginPlay()
{
    Super::BeginPlay();

    if (UTOSGameInstance* GI = GetGameInstance<UTOSGameInstance>())
    {
        GI->OnPlayerControllerReady(this);
		EntityClass = GI->EntityClass;
        PlayerClass = GI->PlayerClass;
    }
    else
    {
        EntityClass = nullptr;
		PlayerClass = nullptr;
    }

    bIsReadyToSync = true;
}

ASyncEntity* ATOSPlayerController::GetEntityById(int32 Id)
{
    if (ASyncEntity** Found = SpawnedEntities.Find(Id))
    {
        return *Found;
    }

    return nullptr;
}

void ATOSPlayerController::HandleCreateEntity(int32 EntityId, FVector Position, FRotator Rotator, int32 Flags)
{
    static int32 CreateEntityCount = 0;
    CreateEntityCount++;

    if (!bIsReadyToSync)
    {
        ClientFileLog(FString::Printf(TEXT("[CREATE ENTITY] #%d ‚ùå Not ready to sync for EntityId: %d"),
            CreateEntityCount, EntityId));
        return;
    }

    // Verificar se a entidade j√° existe para evitar duplica√ß√£o
    if (SpawnedEntities.Contains(EntityId))
    {
        ClientFileLog(FString::Printf(TEXT("[CREATE ENTITY] #%d ‚ö†Ô∏è Entity %d already exists - skipping creation"),
            CreateEntityCount, EntityId));
        return;
    }

    UWorld* World = GetWorld();
    if (!World || !EntityClass)
    {
        ClientFileLog(FString::Printf(TEXT("[CREATE ENTITY] #%d ‚ùå Invalid World or EntityClass for EntityId: %d"),
            CreateEntityCount, EntityId));
        return;
    }

    // Rastrear posi√ß√µes v√°lidas para entidades
    static TMap<int32, FVector> LastValidPositions;

    // Validar posi√ß√£o para evitar valores inv√°lidos
    bool IsValidPosition = true;

    // Verificar NaN
    if (FMath::IsNaN(Position.X) || FMath::IsNaN(Position.Y) || FMath::IsNaN(Position.Z))
    {
        ClientFileLog(FString::Printf(TEXT("[CREATE ENTITY] #%d ‚ö†Ô∏è NaN position for EntityId: %d - Position: %s"),
            CreateEntityCount, EntityId, *Position.ToString()));
        IsValidPosition = false;
    }

    // Verificar posi√ß√£o zero
    bool IsZeroPosition = FMath::IsNearlyZero(Position.X, 0.1f) &&
                          FMath::IsNearlyZero(Position.Y, 0.1f) &&
                          FMath::IsNearlyZero(Position.Z, 0.1f);

    if (IsZeroPosition)
    {
        ClientFileLog(FString::Printf(TEXT("[CREATE ENTITY] #%d ‚ö†Ô∏è Zero position for EntityId: %d - Position: %s"),
            CreateEntityCount, EntityId, *Position.ToString()));

        // Para entidades criadas, n√£o queremos permitir posi√ß√£o zero
        IsValidPosition = false;
    }

    // Se a posi√ß√£o for inv√°lida, tente usar a √∫ltima posi√ß√£o v√°lida conhecida ou uma posi√ß√£o padr√£o
    if (!IsValidPosition)
    {
        if (LastValidPositions.Contains(EntityId))
        {
            Position = LastValidPositions[EntityId];
            ClientFileLog(FString::Printf(TEXT("[CREATE ENTITY] #%d ‚ö†Ô∏è Using last valid position for EntityId: %d - Position: %s"),
                CreateEntityCount, EntityId, *Position.ToString()));
        }
        else
        {
            // Se n√£o temos posi√ß√£o v√°lida anterior, use uma posi√ß√£o padr√£o n√£o-zero
            Position = FVector(100.0f, 100.0f, 100.0f);
            ClientFileLog(FString::Printf(TEXT("[CREATE ENTITY] #%d ‚ö†Ô∏è Using default position for EntityId: %d - Position: %s"),
                CreateEntityCount, EntityId, *Position.ToString()));
        }
    }
    else if (!IsZeroPosition)
    {
        // Atualizar a √∫ltima posi√ß√£o v√°lida conhecida
        LastValidPositions.Add(EntityId, Position);
    }

    // Criar entidade
    FActorSpawnParameters SpawnParams;
    SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;

    ASyncEntity* Entity = World->SpawnActor<ASyncEntity>(EntityClass, Position, Rotator, SpawnParams);

    if (Entity)
    {
        Entity->EntityId = EntityId;
        Entity->SetFlags(static_cast<EEntityState>(Flags));

        // Definir explicitamente a posi√ß√£o e rota√ß√£o para garantir que esteja correta desde o in√≠cio
        Entity->SetActorLocation(Position);
        Entity->SetActorRotation(Rotator);

        // Definir explicitamente os alvos de interpola√ß√£o para a posi√ß√£o atual
        Entity->TargetLocation = Position;
        Entity->TargetRotation = Rotator;

        SpawnedEntities.Add(EntityId, Entity);

        ClientFileLog(FString::Printf(TEXT("[CREATE ENTITY] #%d ‚úÖ Successfully spawned Entity %d at %s"),
            CreateEntityCount, EntityId, *Entity->GetActorLocation().ToString()));
    }
    else
    {
        ClientFileLog(FString::Printf(TEXT("[CREATE ENTITY] #%d ‚ùå Failed to spawn Entity %d"),
            CreateEntityCount, EntityId));
    }
}

void ATOSPlayerController::HandleUpdateEntity(FUpdateEntityPacket data)
{
    if (!bIsReadyToSync) return;

    FDeltaUpdateData DeltaData{};
    DeltaData.Index = data.EntityId;
    DeltaData.EntitiesMask = EEntityDelta::Position | EEntityDelta::Rotation | EEntityDelta::AnimState | EEntityDelta::Velocity | EEntityDelta::Flags;
    DeltaData.Positon = data.Positon;
    DeltaData.Rotator = data.Rotator;
    DeltaData.Velocity = data.Velocity;
    DeltaData.AnimationState = data.AnimationState;
    DeltaData.Flags = data.Flags;

    if (ASyncEntity** Found = SpawnedEntities.Find(data.EntityId))
    {
        ASyncEntity* Entity = *Found;

        if (!Entity)
            return;

        ApplyDeltaData(Entity, DeltaData);
    }
    else if (EntityClass)
    {
        UWorld* World = GetWorld();

        if (!World)
            return;

        FActorSpawnParameters Params;
        Params.Owner = nullptr;
        Params.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
        auto NewEntity = World->SpawnActor<ASyncEntity>(EntityClass, data.Positon, data.Rotator, Params);

        if (NewEntity)
        {
            NewEntity->EntityId = data.EntityId;
            ApplyDeltaData(NewEntity, DeltaData);
            SpawnedEntities.Add(data.EntityId, NewEntity);
        }
    }
}

void ATOSPlayerController::HandleUpdateEntityQuantized(FUpdateEntityQuantizedPacket data)
{
    static int32 HandlerCallCount = 0;
    HandlerCallCount++;

    if (HandlerCallCount <= 15)
    {
        ClientFileLog(FString::Printf(TEXT("=== HandleUpdateEntityQuantized #%d ==="), HandlerCallCount));
        ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] üì® Received EntityId: %d"), data.EntityId));
        ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] üì® Raw Quantized: X=%d Y=%d Z=%d"), data.QuantizedX, data.QuantizedY, data.QuantizedZ));
        ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] üì® Raw Quadrant: X=%d Y=%d"), data.QuadrantX, data.QuadrantY));
        ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] üì® Raw Yaw: %f"), data.Yaw));
        ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] üì® Raw Velocity: %s"), *data.Velocity.ToString()));
        ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] üì® bIsReadyToSync: %s"), bIsReadyToSync ? TEXT("true") : TEXT("false")));
        ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] üì® SpawnedEntities count: %d"), SpawnedEntities.Num()));
    }

    if (!bIsReadyToSync)
    {
        if (HandlerCallCount <= 10)
        {
            ClientFileLog(TEXT("[HANDLER] ‚ùå Not ready to sync, returning"));
        }
        return;
    }

    // Validar quadrantes - valores muito grandes ou pequenos s√£o provavelmente erros
    const int16 MaxQuadrantValue = 100; // Limite razo√°vel para quadrantes
    bool QuadrantAdjusted = false;
    int16 QuadrantX = data.QuadrantX;
    int16 QuadrantY = data.QuadrantY;

    if (QuadrantX < -MaxQuadrantValue || QuadrantX > MaxQuadrantValue)
    {
        QuadrantX = 0;
        QuadrantAdjusted = true;
    }

    if (QuadrantY < -MaxQuadrantValue || QuadrantY > MaxQuadrantValue)
    {
        QuadrantY = 0;
        QuadrantAdjusted = true;
    }

    if (QuadrantAdjusted && HandlerCallCount <= 15)
    {
        ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] ‚ö†Ô∏è Quadrante inv√°lido (%d, %d) - Ajustado para (%d, %d)"),
            data.QuadrantX, data.QuadrantY, QuadrantX, QuadrantY));
    }

    // Calcular a posi√ß√£o mundial para spawn ou compara√ß√£o
    const float Scale = 100.0f; // Match server scale
    const float QuadrantSize = 25600.0f * 4; // Section size * sections per component

    float WorldX = (QuadrantX * QuadrantSize) + (data.QuantizedX * Scale);
    float WorldY = (QuadrantY * QuadrantSize) + (data.QuantizedY * Scale);
    float WorldZ = data.QuantizedZ * Scale;

    FVector WorldPosition = FVector(WorldX, WorldY, WorldZ);
    FRotator WorldRotation = FRotator(0.0f, data.Yaw, 0.0f);

    // Verificar se a posi√ß√£o √© v√°lida
    bool IsValidPosition = true;

    // Verificar valores NaN
    if (FMath::IsNaN(WorldPosition.X) || FMath::IsNaN(WorldPosition.Y) || FMath::IsNaN(WorldPosition.Z))
    {
        ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] ‚ö†Ô∏è Posi√ß√£o NaN detectada para Entity %d"), data.EntityId));
        IsValidPosition = false;
    }

    // Verificar se a posi√ß√£o √© zero (posi√ß√£o inv√°lida comum)
    bool IsZeroPosition = FMath::IsNearlyZero(WorldPosition.X, 0.1f) &&
                          FMath::IsNearlyZero(WorldPosition.Y, 0.1f) &&
                          FMath::IsNearlyZero(WorldPosition.Z, 0.1f);

    // Posi√ß√£o zero √© suspeita, mas n√£o necessariamente inv√°lida para o spawn inicial
    if (IsZeroPosition && HandlerCallCount <= 15)
    {
        ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] ‚ö†Ô∏è Posi√ß√£o zero detectada para Entity %d"), data.EntityId));
    }

    // Se a posi√ß√£o for inv√°lida, tente usar a √∫ltima posi√ß√£o v√°lida conhecida
    static TMap<int32, FVector> LastValidPositions;

    if (!IsValidPosition)
    {
        if (LastValidPositions.Contains(data.EntityId))
        {
            WorldPosition = LastValidPositions[data.EntityId];
            ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] ‚ö†Ô∏è Usando √∫ltima posi√ß√£o v√°lida para Entity %d: %s"),
                data.EntityId, *WorldPosition.ToString()));
        }
        else
        {
            // Se n√£o temos posi√ß√£o v√°lida anterior, use uma posi√ß√£o padr√£o n√£o-zero
            WorldPosition = FVector(100.0f, 100.0f, 100.0f);
            ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] ‚ö†Ô∏è Usando posi√ß√£o padr√£o para Entity %d: %s"),
                data.EntityId, *WorldPosition.ToString()));
        }
    }
    else if (!IsZeroPosition)
    {
        // Atualizar a √∫ltima posi√ß√£o v√°lida conhecida
        LastValidPositions.Add(data.EntityId, WorldPosition);
    }

    if (HandlerCallCount <= 15)
    {
        ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] üßÆ Posi√ß√£o mundial calculada: %s"), *WorldPosition.ToString()));
    }

    if (ASyncEntity** Found = SpawnedEntities.Find(data.EntityId))
    {
        ASyncEntity* Entity = *Found;

        if (!Entity)
        {
            if (HandlerCallCount <= 10)
            {
                ClientFileLog(TEXT("[HANDLER] ‚ùå Entity found but is NULL"));
            }
            return;
        }

        if (HandlerCallCount <= 10)
        {
            ClientFileLog(FString::Printf(TEXT("[HANDLER] ‚úÖ Found existing entity %d, updating..."), data.EntityId));
            ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] üßÆ Entity Current Position: %s"), *Entity->GetActorLocation().ToString()));
        }

        // Para entidades existentes, primeiro definir diretamente a posi√ß√£o para garantir que n√£o fique em (0,0)
        // Isso √© especialmente importante para as primeiras atualiza√ß√µes
        static TMap<int32, int32> EntityUpdateCounts;
        int32& UpdateCount = EntityUpdateCounts.FindOrAdd(data.EntityId, 0);
        UpdateCount++;

        if (UpdateCount <= 3 && !IsZeroPosition)
        {
            // Nas primeiras atualiza√ß√µes, for√ßar a posi√ß√£o diretamente
            Entity->SetActorLocation(WorldPosition);
            Entity->SetActorRotation(WorldRotation);
            ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] üöÄ For√ßando posi√ß√£o inicial para Entity %d: %s"),
                data.EntityId, *WorldPosition.ToString()));
        }

        // Use o m√©todo de atualiza√ß√£o quantizada
        bool IsFalling = (data.Flags & 1) != 0; // Assume bit 0 is IsFalling flag
        Entity->UpdateFromQuantizedNetwork(
            data.QuantizedX, data.QuantizedY, data.QuantizedZ,
            QuadrantX, QuadrantY, data.Yaw,
            data.Velocity, static_cast<uint32>(data.AnimationState), IsFalling
        );

        if (HandlerCallCount <= 15)
        {
            ClientFileLog(FString::Printf(TEXT("[CLIENT RECV] ‚úÖ Entity Updated - New Position: %s"), *Entity->GetActorLocation().ToString()));
        }
    }
    else if (EntityClass)
    {
        if (HandlerCallCount <= 10)
        {
            ClientFileLog(FString::Printf(TEXT("[HANDLER] üÜï Spawning new entity %d..."), data.EntityId));
        }

        UWorld* World = GetWorld();

        if (!World)
        {
            if (HandlerCallCount <= 10)
            {
                ClientFileLog(TEXT("[HANDLER] ‚ùå World is NULL"));
            }
            return;
        }

        // Para novas entidades, n√£o permitir spawn em (0,0,0) a menos que seja explicitamente necess√°rio
        if (IsZeroPosition)
        {
            // Se a posi√ß√£o for zero, tente usar uma posi√ß√£o n√£o-zero padr√£o para o spawn inicial
            WorldPosition = FVector(100.0f, 100.0f, 100.0f);
            ClientFileLog(FString::Printf(TEXT("[HANDLER] ‚ö†Ô∏è Evitando spawn em posi√ß√£o zero para Entity %d, usando: %s"),
                data.EntityId, *WorldPosition.ToString()));
        }

        if (HandlerCallCount <= 10)
        {
            ClientFileLog(FString::Printf(TEXT("[HANDLER] Spawning at world position: %s"), *WorldPosition.ToString()));
            ClientFileLog(FString::Printf(TEXT("[HANDLER] Spawning with rotation: %s"), *WorldRotation.ToString()));
        }

        FActorSpawnParameters Params;
        Params.Owner = nullptr;
        Params.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
        auto NewEntity = World->SpawnActor<ASyncEntity>(EntityClass, WorldPosition, WorldRotation, Params);

        if (NewEntity)
        {
            NewEntity->EntityId = data.EntityId;

            // Definir diretamente a posi√ß√£o e rota√ß√£o para garantir que esteja correta desde o in√≠cio
            NewEntity->SetActorLocation(WorldPosition);
            NewEntity->SetActorRotation(WorldRotation);

            // Definir explicitamente os alvos de interpola√ß√£o para a posi√ß√£o atual
            NewEntity->TargetLocation = WorldPosition;
            NewEntity->TargetRotation = WorldRotation;

            // Atualizar a √∫ltima posi√ß√£o v√°lida conhecida
            if (!IsZeroPosition)
            {
                LastValidPositions.Add(data.EntityId, WorldPosition);
            }

            // Agora chame UpdateFromQuantizedNetwork para configurar anima√ß√µes e outras propriedades
            bool IsFalling = (data.Flags & 1) != 0; // Assume bit 0 is IsFalling flag
            NewEntity->UpdateFromQuantizedNetwork(
                data.QuantizedX, data.QuantizedY, data.QuantizedZ,
                QuadrantX, QuadrantY, data.Yaw,
                data.Velocity, static_cast<uint32>(data.AnimationState), IsFalling
            );

            SpawnedEntities.Add(data.EntityId, NewEntity);

            if (HandlerCallCount <= 10)
            {
                ClientFileLog(FString::Printf(TEXT("[HANDLER] ‚úÖ Entity %d spawned at %s and added to SpawnedEntities"),
                    data.EntityId, *NewEntity->GetActorLocation().ToString()));
            }
        }
        else
        {
            if (HandlerCallCount <= 10)
            {
                ClientFileLog(TEXT("[HANDLER] ‚ùå Failed to spawn entity"));
            }
        }
    }
    else
    {
        if (HandlerCallCount <= 10)
        {
            ClientFileLog(TEXT("[HANDLER] ‚ùå EntityClass is NULL, cannot spawn"));
        }
    }
}

void ATOSPlayerController::HandleDeltaUpdate(FDeltaUpdateData data)
{
    if (!bIsReadyToSync) return;

    if (ASyncEntity** Found = SpawnedEntities.Find(data.Index))
    {
        ASyncEntity* Entity = *Found;
        if (!Entity) return;
        ApplyDeltaData(Entity, data);
    }
    else if (EntityClass)
    {
        UWorld* World = GetWorld();

        if (!World)
            return;

        FActorSpawnParameters Params;
        Params.Owner = nullptr;
        Params.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
        auto NewEntity = World->SpawnActor<ASyncEntity>(EntityClass, data.Positon, data.Rotator, Params);

        if (NewEntity)
        {
            NewEntity->EntityId = data.Index;
            ApplyDeltaData(NewEntity, data);
            SpawnedEntities.Add(data.Index, NewEntity);
        }
    }
}

void ATOSPlayerController::ApplyDeltaData(ASyncEntity* Entity, const FDeltaUpdateData& Data)
{
    constexpr float MaxTeleportDistance = 100.0f;
    constexpr float MaxTeleportAngle = 30.0f;

    if (EnumHasAnyFlags(Data.EntitiesMask, EEntityDelta::Position))
    {
        Entity->SetActorLocation(Data.Positon);
        /*const FVector CurrentLocation = Entity->GetActorLocation();
        const float Distance = FVector::Dist(CurrentLocation, Data.Positon);

        if (Distance > MaxTeleportDistance)
        {
            Entity->SetActorLocation(Data.Positon);
            Entity->TargetLocation = Data.Positon;
        }
        else
        {
            Entity->TargetLocation = Data.Positon;
        }*/
    }

    if (EnumHasAnyFlags(Data.EntitiesMask, EEntityDelta::Rotation))
    {
        Entity->SetActorRotation(Data.Rotator);
        /*const FRotator CurrentRotation = Entity->GetActorRotation();
        const float DeltaAngle = FMath::Abs((CurrentRotation - Data.Rotator).GetNormalized().Yaw);

        if (DeltaAngle > MaxTeleportAngle)
        {
            Entity->SetActorRotation(Data.Rotator);
            Entity->TargetRotation = Data.Rotator;
        }
        else
        {
            Entity->TargetRotation = Data.Rotator;
        }*/
    }

    EEntityState Flags = static_cast<EEntityState>(Data.Flags);
    bool bIsFalling = HasEntityState(Flags, EEntityState::IsFalling);
    FVector Velocity = EnumHasAnyFlags(Data.EntitiesMask, EEntityDelta::Velocity) ? Data.Velocity : FVector::ZeroVector;
    uint32 Anim = EnumHasAnyFlags(Data.EntitiesMask, EEntityDelta::AnimState) ? Data.AnimationState : Entity->AnimationState;
    Entity->AnimationState = Anim;
    Entity->UpdateAnimationFromNetwork(Velocity, Anim, bIsFalling);
}

void ATOSPlayerController::HandleRemoveEntity(int32 EntityId)
{
    static int32 RemoveEntityCount = 0;
    RemoveEntityCount++;

    if (!bIsReadyToSync)
    {
        ClientFileLog(FString::Printf(TEXT("[REMOVE ENTITY] #%d ‚ùå Not ready to sync for EntityId: %d"),
            RemoveEntityCount, EntityId));
        return;
    }

    if (ASyncEntity* const* Found = SpawnedEntities.Find(EntityId))
    {
        ASyncEntity* Entity = *Found;

        if (Entity)
        {
            ClientFileLog(FString::Printf(TEXT("[REMOVE ENTITY] #%d ‚úÖ Removing Entity %d at position %s"),
                RemoveEntityCount, EntityId, *Entity->GetActorLocation().ToString()));
            Entity->Destroy();
        }

        SpawnedEntities.Remove(EntityId);
    }
    else
    {
        ClientFileLog(FString::Printf(TEXT("[REMOVE ENTITY] #%d ‚ö†Ô∏è Entity %d not found for removal"),
            RemoveEntityCount, EntityId));
    }
}
